version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./apache-config.conf:/usr/local/apache2/conf/apache-config.conf
  site:
    profiles:
      - dev
    image: httpd:latest
    ports:
      - '8081:80'
    volumes:
      - ./site:/usr/local/apache2/htdocs
