version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./apache-config.conf:/usr/local/apache2/conf/apache-config.conf